apiVersion: v1
data:
  key: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSU5QYmY4cDdLZXlZSWozZUtFa2J2dmRaNDNsVEZhaHFPSVpCb2JYc2Uyd2EgdGVjaHF1ZXN0MjAyNQ==
kind: Secret
metadata:
  name: techquest
type: Opaque
